application: typemoon-engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app
  secure: optional
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
