application: typemoon-engine
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /yandex_7f382d453a4ab357.txt
  static_files: static/yandex_7f382d453a4ab357.txt
  upload: static/yandex_7f382d453a4ab357.txt
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /.*
  script: main.app
  secure: optional

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
