application: typemoon-engine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app
  secure: optional
- url: /yandex_7f382d453a4ab357.txt
  upload: static/yandex_7f382d453a4ab357.txt
  static_files: static/yandex_7f382d453a4ab357.txt
- url: /robots.txt
  upload: static/robots.txt
  static_files: static/robots.txt
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
